# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenhueCli < Formula
  desc "OpenHue CLI is a command-line interface for interacting with Philips Hue smart lighting systems"
  homepage "https://github.com/openhue/homebrew-cli"
  version "0.8.0"
  license "Apache License 2.0"

  on_macos do
    url "https://github.com/openhue/openhue-cli/releases/download/0.8.0/openhue_Darwin_all.tar.gz"
    sha256 "bfd901fbf71bb51c07b15f89755159bbbe0f6f8c61c092d3f08d8e3e263dd588"

    def install
      bin.install "openhue"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openhue/openhue-cli/releases/download/0.8.0/openhue_Linux_arm64.tar.gz"
      sha256 "f1aba5c8fa4d5c028e7387a0c5f164e40e295f922395b8c619a27c36a202ae10"

      def install
        bin.install "openhue"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/openhue/openhue-cli/releases/download/0.8.0/openhue_Linux_x86_64.tar.gz"
      sha256 "7dbd638429d5891128d9e5a280b2bb0ec34ad1e33c95f0241b928dbc3cc83e60"

      def install
        bin.install "openhue"
      end
    end
  end
end
