# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenhueCli < Formula
  desc "OpenHue CLI is a command-line interface for interacting with Philips Hue smart lighting systems"
  homepage "https://github.com/openhue/homebrew-cli"
  version "0.10"
  license "Apache License 2.0"

  on_macos do
    url "https://github.com/openhue/openhue-cli/releases/download/0.10/openhue_Darwin_all.tar.gz"
    sha256 "dd1d39659f6c05d2af71a6e93b95da92f665c01200f161380a688066d44d266c"

    def install
      bin.install "openhue"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openhue/openhue-cli/releases/download/0.10/openhue_Linux_arm64.tar.gz"
      sha256 "b58b4180728cbea6ac806dd8af1080bbdace76edcea77b61a1d08a26cd9716dd"

      def install
        bin.install "openhue"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/openhue/openhue-cli/releases/download/0.10/openhue_Linux_x86_64.tar.gz"
      sha256 "ae57fdbdff74bb3b400dd0a89ee2b439699caa99110ca576753741c09380e742"

      def install
        bin.install "openhue"
      end
    end
  end
end
